<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Gennadiy Lokhov</Authors>
        <Copyright>Copyright © Gennadiy Lokhov</Copyright>
        <Description>Simple FSharp wrapper for CSharp methods</Description>
        <PackageId>FInvoke</PackageId>
        <PackageTags>fsharp;csharp;wrapper</PackageTags>
        <PackageProjectUrl>https://github.com/glokhov/csharp</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/glokhov/csharp.git</RepositoryUrl>
        <Version>0.5.0</Version>
    </PropertyGroup>
    <ItemGroup>
        <None Include="../../../README.md" Pack="true" Visible="true" PackagePath="/" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="Library.fs" />
    </ItemGroup>
</Project>